console.log("Hello World")
console.log("Hi")
console.log("Hello Everyone")
console.log("Hello People")
console.log("I am Himanshu")
console.log("I love Moter Sports")
console.log("I am Smart")
console.log("I love Moter Sports a lot") 
console.log("I am intelligent")
dkjdhasfdasf
